using System;


class ej10
{
  public static void Do ()
  {
Console.WriteLine("\n[Ejercicio03.10] Declara un conjunto de 100 enteros cuyos valores siguen la serie 1, 3, 5, 7....");

	int[] arrayEnteros = new int[100];
	int i = 0;

	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	arrayEnteros[i] = i * 2 + 1;
	Console.WriteLine(arrayEnteros[i]);
	i = i + 1;
	

   	
	
Console.Write("\n***************\n");
  }
}